import {
    ShoppingBag, Coffee, Car, Home, Zap, Heart, Gift, Briefcase, DollarSign,
    Utensils, Smartphone, Globe, Film, HeartPulse, Sparkles, ShoppingCart,
    Activity, Anchor, Award, Baby, BadgeCheck, BaggageClaim, BarChart,
    Bath, Battery, Bed, Beer, Bell, Bike, Binary, Bird, Bluetooth,
    Bone, Book, BookOpen, Bot, Box, Brain, Brush, Bug, Building,
    Bus, Cake, Camera, Candy, CarFront, Cat, Cherry, ChefHat, Chrome,
    Church, Cigarette, CircleDollarSign, Clapperboard, Clock, Cloud,
    CloudRain, CloudSun, Clover, Club, Code, Coins, Compass, Cookie,
    Cpu, CreditCard, Crown, Dice1, Dice2, Dice3, Dice4,
    Dice5, Dice6, Dog, Drum, Dumbbell, Egg, Eye, Facebook, Fan,
    Feather, FerrisWheel, FileText, FireExtinguisher, Fish, FlaskConical,
    Flower, Flower2, Footprints, Frame, Frown, Fuel, Gamepad, Gamepad2,
    Gauge, Ghost, Gift as GiftIcon, GlassWater, GraduationCap, Grape,
    Guitar, Hammer, HandMetal, HardDrive, Headphones, Headset, Heart as HeartIcon,
    History, Hop, IceCream, Image, Infinity, Instagram, Joystick, Key,
    Keyboard, Landmark, Laptop, Leaf, Library, Lightbulb, LineChart, Link,
    Linkedin, Locate, Lock, Luggage, Magnet, Mail, Map, MapPin, Martini,
    Medal, Megaphone, Menu, MessageCircle, MessageSquare, Mic, Microscope,
    Microwave, Milk, Milestone, Moon, Mountain, Mouse, Music, Network,
    Newspaper, Notebook, Package, Paintbrush, Palette, Paperclip, PartyPopper,
    PawPrint, Pen, PenTool, Pencil, Phone, Piano, PieChart, PiggyBank,
    Pill, Plane, Play, Plug, Plus, Pocket, Podcast, Popcorn, PoundSterling,
    Power, Printer, Puzzle, Quote, Radio, Rat, Receipt, Redo, RefreshCcw,
    Repeat, Rewind, Rocket, Route, Rss, Ruler, Sailboat, Save, Scale,
    Scan, Scissors, ScreenShare, Search, Send, Settings, Share2, Shield,
    Ship, Shirt, ShoppingBag as ShoppingBagIcon, ShoppingCart as ShoppingCartIcon,
    Shovel, ShowerHead, Skull, Slack, Smartphone as SmartphoneIcon, Smile,
    Snowflake, Sofa, Speaker, Sprout, SquareStack, Star, Sticker, Stethoscope,
    Sun, Sunrise, Sunset, Sword, Swords, Syringe, Table, Tablet, Tag,
    Target, Telescope, Tent, Terminal, Thermometer, Ticket, Timer,
    ToggleLeft, ToggleRight, Tornado, Train, Trash2, TreeDeciduous,
    TreePine, Trophy, Truck, Tv, Twitch, Twitter, Umbrella, Underline,
    Undo, Unlink, Unlock, Upload, User, UserCheck, UserMinus, UserPlus,
    Users, Variable, Video, Voicemail, Volume1, Volume2, Wallet, Wand,
    Watch, Waves, Webcam, Wifi, Wine, WrapText, Wrench, X, XCircle,
    Youtube, Zap as ZapIcon, ZoomIn, ZoomOut
} from 'lucide-react-native';

export const CATEGORY_ICONS: { [key: string]: any } = {
    'shopping-bag': ShoppingBag,
    'coffee': Coffee,
    'car': Car,
    'home': Home,
    'zap': Zap,
    'heart': Heart,
    'gift': Gift,
    'briefcase': Briefcase,
    'money': DollarSign,
    'utensils': Utensils,
    'phone': Smartphone,
    'globe': Globe,
    'film': Film,
    'heart-pulse': HeartPulse,
    'sparkles': Sparkles,
    'shopping-cart': ShoppingCart,
    'activity': Activity,
    'anchor': Anchor,
    'award': Award,
    'baby': Baby,
    'badge-check': BadgeCheck,
    'baggage-claim': BaggageClaim,
    'bar-chart': BarChart,
    'bath': Bath,
    'battery': Battery,
    'bed': Bed,
    'beer': Beer,
    'bell': Bell,
    'bike': Bike,
    'binary': Binary,
    'bird': Bird,
    'bluetooth': Bluetooth,
    'bone': Bone,
    'book': Book,
    'book-open': BookOpen,
    'bot': Bot,
    'box': Box,
    'brain': Brain,
    'brush': Brush,
    'bug': Bug,
    'building': Building,
    'bus': Bus,
    'cake': Cake,
    'camera': Camera,
    'candy': Candy,
    'car-front': CarFront,
    'cat': Cat,
    'cherry': Cherry,
    'chef-hat': ChefHat,
    'chrome': Chrome,
    'church': Church,
    'cigarette': Cigarette,
    'circle-dollar': CircleDollarSign,
    'clapperboard': Clapperboard,
    'clock': Clock,
    'cloud': Cloud,
    'cloud-rain': CloudRain,
    'cloud-sun': CloudSun,
    'clover': Clover,
    'club': Club,
    'code': Code,
    'coins': Coins,
    'compass': Compass,
    'cookie': Cookie,
    'cpu': Cpu,
    'credit-card': CreditCard,
    'crown': Crown,
    'dice-1': Dice1,
    'dice-2': Dice2,
    'dice-3': Dice3,
    'dice-4': Dice4,
    'dice-5': Dice5,
    'dice-6': Dice6,
    'dog': Dog,
    'drum': Drum,
    'dumbbell': Dumbbell,
    'egg': Egg,
    'eye': Eye,
    'facebook': Facebook,
    'fan': Fan,
    'feather': Feather,
    'ferris-wheel': FerrisWheel,
    'file-text': FileText,
    'fire-extinguisher': FireExtinguisher,
    'fish': Fish,
    'flask-conical': FlaskConical,
    'flower': Flower,
    'flower2': Flower2,
    'footprints': Footprints,
    'frame': Frame,
    'frown': Frown,
    'fuel': Fuel,
    'gamepad': Gamepad,
    'gamepad2': Gamepad2,
    'gauge': Gauge,
    'ghost': Ghost,
    'gift-icon': GiftIcon,
    'glass-water': GlassWater,
    'graduation-cap': GraduationCap,
    'grape': Grape,
    'guitar': Guitar,
    'hammer': Hammer,
    'hand-metal': HandMetal,
    'hard-drive': HardDrive,
    'headphones': Headphones,
    'headset': Headset,
    'heart-icon': HeartIcon,
    'history': History,
    'hop': Hop,
    'ice-cream': IceCream,
    'image': Image,
    'infinity': Infinity,
    'instagram': Instagram,
    'joystick': Joystick,
    'key': Key,
    'keyboard': Keyboard,
    'laptop': Laptop,
    'leaf': Leaf,
    'library': Library,
    'lightbulb': Lightbulb,
    'line-chart': LineChart,
    'link': Link,
    'linkedin': Linkedin,
    'locate': Locate,
    'lock': Lock,
    'luggage': Luggage,
    'magnet': Magnet,
    'mail': Mail,
    'map': Map,
    'map-pin': MapPin,
    'martini': Martini,
    'medal': Medal,
    'megaphone': Megaphone,
    'menu': Menu,
    'message-circle': MessageCircle,
    'message-square': MessageSquare,
    'mic': Mic,
    'microscope': Microscope,
    'microwave': Microwave,
    'milk': Milk,
    'milestones': Milestone,
    'moon': Moon,
    'mountain': Mountain,
    'mouse': Mouse,
    'music': Music,
    'network': Network,
    'newspaper': Newspaper,
    'notebook': Notebook,
    'package': Package,
    'paintbrush': Paintbrush,
    'palette': Palette,
    'paperclip': Paperclip,
    'party-popper': PartyPopper,
    'paw-print': PawPrint,
    'pen': Pen,
    'pen-tool': PenTool,
    'pencil': Pencil,
    'phone-alt': Phone,
    'piano': Piano,
    'pie-chart': PieChart,
    'piggy-bank': PiggyBank,
    'pill': Pill,
    'plane': Plane,
    'play': Play,
    'plug': Plug,
    'plus': Plus,
    'pocket': Pocket,
    'podcast': Podcast,
    'popcorn': Popcorn,
    'pound-sterling': PoundSterling,
    'power': Power,
    'printer': Printer,
    'puzzle': Puzzle,
    'quote': Quote,
    'radio': Radio,
    'rat': Rat,
    'receipt-alt': Receipt,
    'redo': Redo,
    'refresh': RefreshCcw,
    'repeat': Repeat,
    'rewind': Rewind,
    'rocket': Rocket,
    'route': Route,
    'rss': Rss,
    'ruler': Ruler,
    'sailboat': Sailboat,
    'save': Save,
    'scale': Scale,
    'scan': Scan,
    'scissors': Scissors,
    'screen-share': ScreenShare,
    'search': Search,
    'send': Send,
    'settings': Settings,
    'share-2': Share2,
    'shield': Shield,
    'ship': Ship,
    'shirt': Shirt,
    'shopping-bag-alt': ShoppingBagIcon,
    'shopping-cart-alt': ShoppingCartIcon,
    'shovel': Shovel,
    'shower-head': ShowerHead,
    'skull': Skull,
    'slack': Slack,
    'smartphone-alt': SmartphoneIcon,
    'smile': Smile,
    'snowflake': Snowflake,
    'sofa': Sofa,
    'speaker': Speaker,
    'sprout': Sprout,
    'square-stack': SquareStack,
    'star': Star,
    'sticker': Sticker,
    'stethoscope': Stethoscope,
    'sun': Sun,
    'sunrise': Sunrise,
    'sunset': Sunset,
    'sword': Sword,
    'swords': Swords,
    'syringe': Syringe,
    'table': Table,
    'tablet': Tablet,
    'tag': Tag,
    'target': Target,
    'telescope': Telescope,
    'tent': Tent,
    'terminal': Terminal,
    'thermometer': Thermometer,
    'ticket': Ticket,
    'timer': Timer,
    'toggle-left': ToggleLeft,
    'toggle-right': ToggleRight,
    'tornado': Tornado,
    'train': Train,
    'trash-2': Trash2,
    'tree-deciduous': TreeDeciduous,
    'tree-pine': TreePine,
    'trophy': Trophy,
    'truck': Truck,
    'tv': Tv,
    'twitch': Twitch,
    'twitter': Twitter,
    'umbrella': Umbrella,
    'underline': Underline,
    'undo': Undo,
    'unlink': Unlink,
    'unlock': Unlock,
    'upload': Upload,
    'user': User,
    'user-check': UserCheck,
    'user-minus': UserMinus,
    'user-plus': UserPlus,
    'users': Users,
    'variable': Variable,
    'video': Video,
    'voicemail': Voicemail,
    'volume-1': Volume1,
    'volume-2': Volume2,
    'wallet': Wallet,
    'wand': Wand,
    'watch': Watch,
    'waves': Waves,
    'webcam': Webcam,
    'wifi': Wifi,
    'wine': Wine,
    'wrap-text': WrapText,
    'wrench': Wrench,
    'x': X,
    'x-circle': XCircle,
    'youtube': Youtube,
    'landmark': Landmark,
    'zap-alt': ZapIcon,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut
};
